name: on-push-do-doco
on:
  # Only update the docs on main, to reduce the chance of conflicts
  push:
    branches:
      - main
      - documentation-tocs
jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run MarkdownSnippets
      run: |
        dotnet tool install --global MarkdownSnippets.Tool
        mdsnippets ${GITHUB_WORKSPACE}
      shell: bash
    - name: Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "[docs] Regenerate tables of contents" -a  || echo "nothing to commit"
        remote="https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
        branch="${GITHUB_REF:11}"
        git push "${remote}" ${branch} || echo "nothing to push"
      shell: bash
